container:
  image: node:latest

env:
  CIRRUS_VAULT_URL: https://vault.sonar.build:8200
  CIRRUS_VAULT_AUTH_PATH: jwt-cirrusci
  CIRRUS_VAULT_ROLE: cirrusci-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}
  NPM_CONFIG_registry: https://repox.jfrog.io/artifactory/api/npm/npm
  NPM_CONFIG_//repox.jfrog.io/artifactory/api/npm/:_authToken: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]

validate_build_task:
  validate_build_script:
    - npm run build
    # the check-committed.sh script should always be executed last
    - ./scripts/check-committed.sh

test_task:
  restore_script:       # Restore DEV dependencies that are not present in the repo due to .gitignore of /node_modules/ to reduce the checkout size in production.
    - npm install
  test_script:
    - npm run test
