container:
  image: node:latest

validate_build_task:
  validate_build_script:
    - npm run build
    # the check-committed.sh script should always be executed last
    - ./scripts/check-committed.sh

test_task:
  test_script:
    - npm run test
