container:
  image: node:latest

QA:
  apply_changes_and_check_script:
    - npm run build
    # the check-committed.sh script should always be executed last
    - ./scripts/check-committed.sh
  unit_test_script:
    - npm run test
