name: 'Move card back to selected column after review'
description: 'Move fixed issue or PR card to selected column and assign it to the PR author'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  column-id:
    description: 'ID of the Kanban column where the card should be moved to'
    required: true
runs:
  using: 'node16'
  main: 'MoveCardAfterReview.js'
