name: 'Move card after submitting a review'
description: 'Move fixed Jira tickets using the "Request Changes" or "Approved" transition after submitting a review on a pull request.'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  jira-user:
    description: 'Jira auth User'
    required: true
  jira-token:
    description: 'Jira auth Token'
    required: true
  is-eng-xp-squad:
    description: 'Repo is owned by Engineering Experience Squad'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: '../dist/SubmitReview/Index.js'
