name: 'Move card back to "In Progress" or "Review Approved" column'
description: 'Move fixed issue or PR card to "In Progress" or "Review Approved" column and assign it to the PR author'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  request-changes-column-id:
    description: 'ID of the Kanban column where the card should be moved to when changes are requested'
    required: true
  approve-column-id:
    description: 'ID of the Kanban column where the card should be moved to when PR is approved'
    required: true
runs:
  using: 'node16'
  main: 'SubmitReview.js'
