name: 'Move card to "Review in progress" column'
description: 'Move fixed issue or PR card to "Review in progress" column and assign it to the reviewer'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  column-id:
    description: 'ID of the Kanban column where the card should be moved to'
    required: true
  project-number:
    description: 'The project number when Projects V2 is used'
    required: false
runs:
  using: 'node16'
  main: '../dist/MoveCardToReview/MoveCardToReview.js'
