name: 'Create Jira Issue for PR without issue reference'
description: 'Create Jira Issue for PR that does not reference any Jira issue in its title'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  jira-user:
    description: 'Jira auth user'
    required: true
  jira-token:
    description: 'Jira auth Token'
    required: true
  jira-project:
    description: 'Jira project key'
    required: false
  additional-fields:
    description: 'Additional fields to be added to the Jira issue'
    required: false
  is-eng-xp-squad:
    description: 'Repo is owned by Engineering Experience Squad'
    required: false
    default: 'false'
  fallback-team:
    description: 'Jira Team name to be used as a default fallback'
    required: false
runs:
  using: 'node20'
  main: '../dist/PullRequestCreated/PullRequestCreated.js'
