name: 'Create Jira Issue for PR without issue reference'
description: 'Create Jira Issue for PR that does not reference any Jira issue in its title'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  jira-user:
    description: 'Jira auth user'
    required: true
  jira-token:
    description: 'Jira auth Token'
    required: true
  jira-project:
    description: 'Jira project key'
    required: true
  additional-fields:
    description: 'Additional fields to be added to the Jira issue'
    required: false
runs:
  using: 'node20'
  main: '../dist/PullRequestCreated/PullRequestCreated.js'
