name: 'Create Jira Issue when Pull Request Created if needed'
description: 'Create Jira Issue when Pull Request Created if needed and link mentioned parent'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  jira-user:
    description: 'Jira auth user'
    required: true
  jira-token:
    description: 'Jira auth Token'
    required: true
  jira-project:
    description: 'Jira project key'
    required: true
runs:
  using: 'node20'
  main: '../dist/PullRequestCreated/PullRequestCreated.js'
