name: 'Assign card to sender'
description: 'Assign Kanban card to the sender of the event'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
runs:
  using: 'node16'
  main: '../dist/AssignCardToSender/AssignCardToSender.js'
