name: 'Toggle lock branch'
description: 'Modify branch protection rules to lock or unlock the branch'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  branch-pattern:
    description: 'Pattern of the branch protection rule to modify.'
    required: false
    default: 'master'
runs:
  using: 'node16'
  main: 'ToggleLockBranch.js'
