
# FIXME: This entire file needs to be adjusted

name: 'FIXME Move card to "Review in progress" column'
description: 'FIXME Move fixed issue or PR card to "Review in progress" column and assign it to the reviewer'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  jira-user:
    description: 'Jira auth User'
    required: true
  jira-token:
    description: 'Jira auth Token'
    required: true
runs:
  using: 'node16'
  main: '../dist/RequestReview/RequestReview.js'
