name: 'Move card to "Review in progress" column - v2'
description: 'Move fixed issue or PR card to "Review in progress" column and assign it to the reviewer'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  column-id:
    description: 'ID of the Kanban column where the card should be moved to'
    required: true
  project-number:
    description: 'The number of the project'
    required: true
  is-org:
    description: 'Boolean representing if the action is for an organization or a user. Defaults to "true". Set to "false" when using for a user.'
    required: false
runs:
  using: 'node16'
  main: '../dist/MoveCardToReview-v2/MoveCardToReviewV2.js'
