name: 'Create card for issue from label'
description: 'Create card for issue in a project column determined by the issue label'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  project-id:
    description: 'ID of the Kanban project where the card should be created'
    required: true
  label-prefix:
    description: 'Prefix of the label that activates this action'
    required: false
    default: 'Type:'
runs:
  using: 'node16'
  main: '../dist/CreateCardForIssueFromLabel/index.js'
