name: 'Crate card for issue from label'
description: 'Crate card for issue in a project column determined by issue label'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  project-id:
    description: 'ID of the Kanban project where the card should be created'
    required: true
  label-prefix:
    description: 'Prefix of the label that activates this action'
    required: false
    default: 'Type:'
runs:
  using: 'node16'
  main: 'CreateCardForIssueFromLabel.js'
