name: 'Move card back to selected column after review - V2'
description: 'Move fixed issue or PR card to selected column and assign it to the PR author'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  column-id:
    description: 'ID of the Kanban column where the card should be moved to'
    required: true
  project-number:
    description: 'The number of the project'
    required: true
runs:
  using: 'node16'
  main: '../dist/MoveCardAfterReview-v2/MoveCardAfterReviewV2.js'
