name: 'Crate card for issue'
description: 'Crate card for issue in selected column'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  column-id:
    description: 'ID of the Kanban column where the card should be created'
    required: true
runs:
  using: 'node16'
  main: 'CreateCardForIssue.js'
