name: 'Copy labels from mentioned issues to PR'
description: 'Copy labels from mentioned issues to PR'
inputs:
  github-token:
    description: 'GitHub auth Token'
    required: true
  label-prefix:
    description: 'Label prefix that should be copied. Empty value will copy all labels.'
    default: 'Sprint:'
runs:
  using: 'node16'
  main: '../dist/CopyLabelToPR/CopyLabelToPR.js'
