name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate-build:
    name: Validate build files
    runs-on: ubuntu-latest-large
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

#      - name: Restore dev dependencies
#        run: npm install

      - name: Build
        run: npm run build

      - name: Validate committed files
        run: ./scripts/check-committed.sh

  test:
    name: Run tests
    runs-on: ubuntu-latest-large
    permissions:
      id-token: write
      contents: write
    env:
      NPM_CONFIG_registry: https://repox.jfrog.io/artifactory/api/npm/npm

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2


        #FIXME
      - name: List environment variable names
        run: printenv | cut -d= -f1


      - id: secrets
        uses: SonarSource/vault-action-wrapper@v3
        with:
          secrets: |
            development/artifactory/token/{REPO_OWNER_NAME_DASH}-private-reader access_token | REPOX_TOKEN;

        #FIXME
      - name: List environment variable names
        run: printenv | cut -d= -f1

      - name: Set NPM auth token env var
        run: echo "NPM_CONFIG_//repox.jfrog.io/artifactory/api/npm/:_authToken=$REPOX_TOKEN" >> $GITHUB_ENV

        #FIXME
      - name: List environment variable names
        run: printenv | cut -d= -f1

        # Restore DEV dependencies that are not present in the repo due to .gitignore of /node_modules/ to reduce the checkout size in production.
      - name: Restore dev dependencies
        run: npm install

      - name: Run tests
        run: npm run test
