name: Build

on:
  pull_request:

jobs:
  debug:
    name: Debug
    runs-on: github-windows-latest-s

    steps:
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ${{ runner.temp }}\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}\scanner
      - name: Build and analyze
        shell: powershell
        run: |
          ${{ runner.temp }}\scanner\dotnet-sonarscanner
